"""empty message

Revision ID: 5b86a181f21f
Revises: d3d21f86f6c0
Create Date: 2025-08-23 15:00:22.695355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b86a181f21f'
down_revision = 'd3d21f86f6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_user_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_user_key', ['user'])

    # ### end Alembic commands ###
